# Generated by Django 4.2.7 on 2024-03-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helmdectpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
